language: elixir
elixir:
- 1.2.3
otp_release:
- 18.2.1
addons:
  ssh_known_hosts: cryptoclub.com.br
before_deploy:
  - sudo apt-get update
  - sudo apt-get install software-properties-common
  - sudo apt-add-repository ppa:ansible/ansible -y
  - sudo apt-get update -qq
  - sudo apt-get install ansible -y
  - export APP_VERSION=`mix run -e "IO.puts(EthPrice.Mixfile.project[:version])" --no-start --no-compile --no-deps-check`
  - ansible-playbook -i dist/production dist/build.yml --connection=local -vvvv
deploy:
  provider: releases
  api_key:
    secure: asZTfGIgvK+duHRQMYFHJ01d3IVZmx1+JZ8gSQuF/S7+m74Q8V42QM/j2nSMxj9v84HZ79z+DDEtDxIfTMgilxDi0y6anglcn1t8/3djPIujUXJ0WtMJ7+nKGIhPdtQDQwTOqu4Z6ECUX2G/APDKSfaV5IOM1uwWkM7+Rzs71SkvAGbPE4WsGX1DwxRM8lfedleS7mfsIEahuBhSka6gzaf7mQjtrJEgcORx2oISMDhFHgg4P5ZfNxTCOe5iEaw09XC9SdjGT4wjH2Yej49713G7XfMiFmzN4BSQF4vh7/wRfzd/c9xrImGxnVS9y4IKI/fMN/B/OxBk+PWJTpHoRgasTdmPGIMgkbcorhis5x+0tZpUeFkAb5szx4vR+yWwWpksFNW96qaPJS9X7FAXDKmI0cFtvYwW3esrlKTiO6bz4cAMP9xvY+47g4pGzgsIDa3wO33hgQEnfKipcdWvwijpezsAilscAC7JoptXnPY5asaabSjudfgIixR5uwL4fkyc3S+KUJBNi6zpzp/r0g1J9pTcuJp6U3YCMF3GDjEmrPfWW19v7up4mqKdLcNu4Y6TufBVqglKNsG9XRXnbK4/xzvWKRNiiBO9/XFWJRr9pcUbFLH7j4Al74nU+c2+NJDsaN7LEub8uIWD4bBpqc+XrHeX+o8wOy2KFyn+k5c=
  file: rel/eth_price/releases/$APP_VERSION/eth_price.tar.gz
  on:
    tags: true
    repo: esdrasedu/eth_price
after_deploy:
  - openssl aes-256-cbc -K $encrypted_4eca667de08e_key -iv $encrypted_4eca667de08e_iv -in dist/eth_price.pem.enc -out dist/eth_price.pem -d
  - sudo chmod 600 dist/eth_price.pem
  - scp -i dist/eth_price.pem rel/eth_price/releases/$APP_VERSION/eth_price.tar.gz root@cryptoclub.com.br:/tmp/eth_price_$APP_VERSION.tar.gz 
  - ansible-playbook -i dist/production dist/deploy.yml --extra-vars version=$APP_VERSION -vvvv
